theme: jekyll-theme-tactile
title: Eu sou Jair Bolsonaro
description: Sou de extrema direita, racista, machista, homofóbico, autoritário, defendo milícias e a tortura, e aqui estão alguns dos meus pensamentos.
